nixos: Fix btrfs-subvol-rm-r subvol matching
Previously when trying to match subvolumes with parent '123', parent
'1234' or other ids with the target parent prefix would get matched.

diff --git a/nix/packages/misc/btrfs-subvol-rm-r b/nix/packages/misc/btrfs-subvol-rm-r
--- a/nix/packages/misc/btrfs-subvol-rm-r
+++ b/nix/packages/misc/btrfs-subvol-rm-r
@@ -2,15 +2,15 @@
 set -euo pipefail
 
 if [[ "$#" -ne 1 ]]; then
-    echo "Invalid parameters."
-    exit 1
+  echo "Invalid parameters."
+  exit 1
 fi
 
 rec_sub_del () {
-    for child in $(btrfs sub list "$1" | awk '/top level '"$2"'/{print $2}'); do
-        rec_sub_del "$1" "$child"
-    done
-    btrfs subvolume delete -i "$2" "$1" | sed "s|$1||"
+  for child in $(btrfs sub list "$1" | awk '/top level '"$2"'\>/{print $2}'); do
+    rec_sub_del "$1" "$child"
+  done
+  btrfs subvolume delete -i "$2" "$1" | sed "s|$1||"
 }
 
 id=$(btrfs subvolume show "$1" | awk '/Subvolume ID:/{print $3}')
